// Purchase additem 
export const PURCHASE_ADDITEM_REQUEST = "PURCHASE_ADDITEM_REQUEST";
export const PURCHASE_ADDITEM_SUCCESS = "PURCHASE_ADDITEM_SUCCESS";
export const PURCHASE_ADDITEM_FAIL = "PURCHASE_ADDITEM_FAIL";



export const ADD_SALESITEM_REQUEST = "ADD_SALESITEM_REQUEST";
export const ADD_SALESITEM_SUCCESS = "ADD_SALESITEM_SUCCESS";
export const ADD_SALESITEM_FAIL = "ADD_SALESITEM_FAIL";


export const PURCHASE_DETAIL_REQUEST = "PURCHASE_DETAIL_REQUEST";
export const PURCHASE_DETAIL_SUCCESS = "PURCHASE_DETAIL_SUCCESS";
export const PURCHASE_DETAIL_FAIL = "PURCHASE_DETAIL_FAIL";

export const PURCHASE_UPDATE_REQUEST = "PURCHASE_UPDATE_REQUEST";
export const PURCHASE_UPDATE_SUCCESS = "PURCHASE_UPDATE_SUCCESS";
export const PURCHASE_UPDATE_FAIL = "PURCHASE_UPDATE_FAIL";

export const PURCHASE_DELETE_REQUEST = "PURCHASE_DELETE_REQUEST";
export const PURCHASE_DELETE_SUCCESS = "PURCHASE_DELETE_SUCCESS";
export const PURCHASE_DELETE_FAIL = "PURCHASE_DELETE_FAIL";

export const BILL_DELETE_REQUEST = "BILL_DELETE_REQUEST";
export const BILL_DELETE_SUCCESS = "BILL_DELETE_SUCCESS";
export const BILL_DELETE_FAIL = "BILL_DELETE_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
//Purchase
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const FETCH_USERBILL_REQUEST = " FETCH_USERBILL_REQUEST"
export const FETCH_USERBILL_SUCCESS = " FETCH_USERBILL_SUCCESS"
export const FETCH_USERBILL_FAIL = " FETCH_USERBILL_FAIL"


export const url = "https://inventoryvijainatesh.herokuapp.com/"